add element config files
frc-web-components/components pull request #4
Opened 2022-02-15 02:43 UTC by awordforthat

I was being dumb, I was logged into the wrong windows account, so it was using the wrong credentials

2022-02-17 20:57 UTC, amorygalili requested changes

2022-02-17 20:57 UTC, amorygalili commented on src/elements/vaadin-elements/index.js
> +        helperText: { type: 'String', default: 'Helper text' }
`default` should be `defaultValue`. Also, the default values should be based on the default value set in the component/documented in the component library's documentation. In this case no value is set so the default value should be an empty string.

2022-02-17 20:57 UTC, amorygalili commented on src/elements/vaadin-elements/index.js
> +              </vaadin-vertical-layout>
Since this is meant to be used by other teams I'd leave out anything specific to our team.

2022-02-17 20:57 UTC, amorygalili commented on src/elements/vaadin-elements/index.js
> +        step: { type: 'Number', default: 1 },
It looks like by default these values are not set by the component. The `defaultValue` should probably undefined or null in this case. I'm not sure if the dashboard is able to handle undefined or null values, so you'll have to test.

2022-02-17 20:57 UTC, amorygalili commented on src/elements/vaadin-elements/index.js
> +        { html: `<vaadin-date-picker label="Sample Date Picker"></vaadin-date-picker>` }
Looks like you have a label prop here. Would this be useful to add to the list of properties?

2022-02-19 00:52 UTC, awordforthat commented on src/elements/vaadin-elements/index.js
> +        { html: `<vaadin-date-picker label="Sample Date Picker"></vaadin-date-picker>` }
yes, didn't catch that, thanks

2022-02-19 01:13 UTC, awordforthat commented on src/elements/vaadin-elements/index.js
> +        step: { type: 'Number', default: 1 },
Tested this, and it looks fine to just have undefined/default. I left the demo using fixed values since I thought that would be more useful to students/testers.

2022-02-19 01:13 UTC, awordforthat commented on src/elements/vaadin-elements/index.js
> +              </vaadin-vertical-layout>
Ah, good point. Will change.

2022-02-23 00:05 UTC, merged